# Generated by Django 2.1.5 on 2020-06-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinosTuristicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCiudad', models.CharField(max_length=32)),
                ('descripcionCiudad', models.TextField(max_length=128)),
                ('imagenCiudad', models.ImageField(upload_to='')),
                ('precioTour', models.IntegerField()),
                ('ofertaTour', models.BooleanField(default=False)),
            ],
        ),
    ]
